CREATED_STATE = "created"
LOADED_STATE = "loaded"
READ_STATE = "read"
COMMENT_STATES = (CREATED_STATE, LOADED_STATE, READ_STATE)
EXCEPTION_MSG_TITLE = "Oops!"
FILE_EXCEPTION_MSG_TEXT = "Sorry! We were embarrassed that an error occurred with the text file."
STATUS_BAR_LOAD_COMMENTS_TEXT = "Carregando comentários..."
STATUS_BAR_LOADED_COMMENTS_TEXT = " comentários carregados. 0 lidos."
PLAY_TIME_STATE = True
STOP_TIME_STATE = False